#pragma once

enum class DataType
{
	INDEX_TYPE = 0x10000,
	FIX_LEN = 0x20000,
	ARRAY_TYPE = 0x40000,
	AGGR_TYPE = 0x80000,
	AUTO_INC_TYPE = 0x100000,

	BYTE = AUTO_INC_TYPE + AGGR_TYPE + FIX_LEN + 1,
	SHORT = AUTO_INC_TYPE + AGGR_TYPE + INDEX_TYPE + FIX_LEN + 2,
	INT = AUTO_INC_TYPE + AGGR_TYPE + INDEX_TYPE + FIX_LEN + 3,
	LONG = AUTO_INC_TYPE + AGGR_TYPE + INDEX_TYPE + FIX_LEN + 4,

	UBYTE = AUTO_INC_TYPE + AGGR_TYPE + FIX_LEN + 1,
	USHORT = AUTO_INC_TYPE + AGGR_TYPE + INDEX_TYPE + FIX_LEN + 2,
	UINT = AUTO_INC_TYPE + AGGR_TYPE + INDEX_TYPE + FIX_LEN + 3,
	ULONG = AUTO_INC_TYPE + AGGR_TYPE + INDEX_TYPE + FIX_LEN + 4,

	CHAR = INDEX_TYPE + FIX_LEN + ARRAY_TYPE + 5,
	VARCHAR = INDEX_TYPE + ARRAY_TYPE + 6,
	DATETIME = INDEX_TYPE + FIX_LEN + 7,
	FLOAT = AGGR_TYPE + INDEX_TYPE + FIX_LEN + 8,
	DOUBLE = AGGR_TYPE + INDEX_TYPE + FIX_LEN + 9,
	BLOB = ARRAY_TYPE + 10,
	BOOL = FIX_LEN + 11,
	COMPRESS = ARRAY_TYPE + 100,
};

